//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopyFolders2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lbl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lbl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CopyFolders2.Lbl", typeof(Lbl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data processing has been interrupted from the user.
        /// </summary>
        internal static string aborted {
            get {
                return ResourceManager.GetString("aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also copy files:.
        /// </summary>
        internal static string AlsoCopy {
            get {
                return ResourceManager.GetString("AlsoCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        internal static string AlsoHidden {
            get {
                return ResourceManager.GetString("AlsoHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string AlsoSystem {
            get {
                return ResourceManager.GetString("AlsoSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string AndThe {
            get {
                return ResourceManager.GetString("AndThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates now.
        /// </summary>
        internal static string CheckNow {
            get {
                return ResourceManager.GetString("CheckNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically check for updates.
        /// </summary>
        internal static string CheckUpdates {
            get {
                return ResourceManager.GetString("CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string CopyButton {
            get {
                return ResourceManager.GetString("CopyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy all new or modified files from these folders....
        /// </summary>
        internal static string CopyFrom {
            get {
                return ResourceManager.GetString("CopyFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... to these (new subdirectories will be created automatically).
        /// </summary>
        internal static string CopyTo {
            get {
                return ResourceManager.GetString("CopyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy only files created or modified between.
        /// </summary>
        internal static string Dates {
            get {
                return ResourceManager.GetString("Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deutsch.
        /// </summary>
        internal static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to english.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to español.
        /// </summary>
        internal static string es {
            get {
                return ResourceManager.GetString("es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to français.
        /// </summary>
        internal static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the language:.
        /// </summary>
        internal static string InfoLangs {
            get {
                return ResourceManager.GetString("InfoLangs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to italiano.
        /// </summary>
        internal static string it {
            get {
                return ResourceManager.GetString("it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open CF2.log.
        /// </summary>
        internal static string OpenButton {
            get {
                return ResourceManager.GetString("OpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to polski.
        /// </summary>
        internal static string pl {
            get {
                return ResourceManager.GetString("pl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &quot;Copy&quot; to copy the listed files, if new or modified. Press the &quot;List&quot; button or  the &quot;Esc&quot; key to  return to the listing or to cancel copying at  run..
        /// </summary>
        internal static string PressCopy {
            get {
                return ResourceManager.GetString("PressCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the &quot;List&quot; button to generate a list of the selected files. Press again the &quot;List&quot; button or the &quot;Esc&quot; key to stop processing at any time..
        /// </summary>
        internal static string PressStart {
            get {
                return ResourceManager.GetString("PressStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to português.
        /// </summary>
        internal static string pt {
            get {
                return ResourceManager.GetString("pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows to display.
        /// </summary>
        internal static string Rows {
            get {
                return ResourceManager.GetString("Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to русский.
        /// </summary>
        internal static string ru {
            get {
                return ResourceManager.GetString("ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Basename: click an image to automatically insert the source path basename folder (the last one) into the destination path.
        ///Left Alt+click to remove the last basename from the destination path.
        /// </summary>
        internal static string TipAutoBase {
            get {
                return ResourceManager.GetString("TipAutoBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basename only: if checked are copied only the destination basename folder files (excluding subfolders).
        /// </summary>
        internal static string TipBasename {
            get {
                return ResourceManager.GetString("TipBasename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the number of previous versions of backup files to save.
        /// </summary>
        internal static string TipBkps {
            get {
                return ResourceManager.GetString("TipBkps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compact: Eliminates empty rows by compacting full ones at the top.
        /// </summary>
        internal static string TipComp {
            get {
                return ResourceManager.GetString("TipComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert  characters and/or  wildcards to filter file names.
        ///Start with &quot;!=&quot; for negative search (see the Help).
        /// </summary>
        internal static string TipMask {
            get {
                return ResourceManager.GetString("TipMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --------------------------------.
        /// </summary>
        internal static string Trattini {
            get {
                return ResourceManager.GetString("Trattini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading updates. Try later..
        /// </summary>
        internal static string UpdateError {
            get {
                return ResourceManager.GetString("UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program is up to date.
        /// </summary>
        internal static string UpToDate {
            get {
                return ResourceManager.GetString("UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.0.1.4.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.
        /// </summary>
        internal static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中文.
        /// </summary>
        internal static string zh {
            get {
                return ResourceManager.GetString("zh", resourceCulture);
            }
        }
    }
}
