//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopyFolders2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CopyFolders2.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must check at least one row!.
        /// </summary>
        public static string AlmostOne {
            get {
                return ResourceManager.GetString("AlmostOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CopyFolders2.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical error .
        /// </summary>
        public static string CriticalError {
            get {
                return ResourceManager.GetString("CriticalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error .
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BO (basename only) is checked.
        /// </summary>
        public static string logBoChecked {
            get {
                return ResourceManager.GetString("logBoChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checked.
        /// </summary>
        public static string logChecked {
            get {
                return ResourceManager.GetString("logChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied.
        /// </summary>
        public static string logCopied {
            get {
                return ResourceManager.GetString("logCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of the files copy.
        /// </summary>
        public static string logCopy {
            get {
                return ResourceManager.GetString("logCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy between.
        /// </summary>
        public static string logCopyBetween {
            get {
                return ResourceManager.GetString("logCopyBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy hidden files.
        /// </summary>
        public static string logCopyHidden {
            get {
                return ResourceManager.GetString("logCopyHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy system files.
        /// </summary>
        public static string logCopySystem {
            get {
                return ResourceManager.GetString("logCopySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination path is.
        /// </summary>
        public static string logDestination {
            get {
                return ResourceManager.GetString("logDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing.
        /// </summary>
        public static string logExisting {
            get {
                return ResourceManager.GetString("logExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error.
        /// </summary>
        public static string logFatalError {
            get {
                return ResourceManager.GetString("logFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of new or modified files to copy.
        /// </summary>
        public static string logFileToCopy {
            get {
                return ResourceManager.GetString("logFileToCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found.
        /// </summary>
        public static string logFound {
            get {
                return ResourceManager.GetString("logFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final list of detected errors.
        /// </summary>
        public static string logGotErrors {
            get {
                return ResourceManager.GetString("logGotErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: files list is sorted.
        /// </summary>
        public static string logListIsSorted {
            get {
                return ResourceManager.GetString("logListIsSorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask is.
        /// </summary>
        public static string logMaskIs {
            get {
                return ResourceManager.GetString("logMaskIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of files that match your settings. Press the &apos;Copy&apos; button to copy them to the Dest path.
        /// </summary>
        public static string logMatchList {
            get {
                return ResourceManager.GetString("logMatchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No copy errors.
        /// </summary>
        public static string logNoCopyErr {
            get {
                return ResourceManager.GetString("logNoCopyErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files new or modified in the row n.
        /// </summary>
        public static string logNoNew {
            get {
                return ResourceManager.GetString("logNoNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No read errors.
        /// </summary>
        public static string logNoReadErr {
            get {
                return ResourceManager.GetString("logNoReadErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No skipped files / directories.
        /// </summary>
        public static string logNoSkipped {
            get {
                return ResourceManager.GetString("logNoSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Present.
        /// </summary>
        public static string logNotPresent {
            get {
                return ResourceManager.GetString("logNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row N.
        /// </summary>
        public static string logRowN {
            get {
                return ResourceManager.GetString("logRowN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search of files date.
        /// </summary>
        public static string logSearch {
            get {
                return ResourceManager.GetString("logSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped.
        /// </summary>
        public static string logSkipped {
            get {
                return ResourceManager.GetString("logSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final list of skipped files or skipped directories.
        /// </summary>
        public static string logSkippedList {
            get {
                return ResourceManager.GetString("logSkippedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting path is.
        /// </summary>
        public static string logStarting {
            get {
                return ResourceManager.GetString("logStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Stopped from the user ***.
        /// </summary>
        public static string logStopped {
            get {
                return ResourceManager.GetString("logStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string Mask {
            get {
                return ResourceManager.GetString("Mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The control becomes clickable only if both the source and destination folders have been set!.
        /// </summary>
        public static string msg_BothEmpty {
            get {
                return ResourceManager.GetString("msg_BothEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t check the checkbox: the starting path no more exist!.
        /// </summary>
        public static string msg_CantCheck {
            get {
                return ResourceManager.GetString("msg_CantCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more previously selected folders no longer exist (red background).
        /// </summary>
        public static string msg_DontExist {
            get {
                return ResourceManager.GetString("msg_DontExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All configuration data will be erased..
        /// </summary>
        public static string msg_Erased {
            get {
                return ResourceManager.GetString("msg_Erased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting path has not basename folder!.
        /// </summary>
        public static string msg_NoBasename {
            get {
                return ResourceManager.GetString("msg_NoBasename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No .log file at this moment.
        /// </summary>
        public static string msg_NoLog {
            get {
                return ResourceManager.GetString("msg_NoLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WildCards are not allowed in negative masks! See the Help..
        /// </summary>
        public static string msg_NoWildCards {
            get {
                return ResourceManager.GetString("msg_NoWildCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program is already running!.
        /// </summary>
        public static string msg_Running {
            get {
                return ResourceManager.GetString("msg_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start path and destination path must be different!.
        /// </summary>
        public static string msg_SamePaths {
            get {
                return ResourceManager.GetString("msg_SamePaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder.
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accessible directories for a size of.
        /// </summary>
        public static string txtAccessibleDir {
            get {
                return ResourceManager.GetString("txtAccessibleDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accessible files that match your settings  in.
        /// </summary>
        public static string txtAccessibleFiles {
            get {
                return ResourceManager.GetString("txtAccessibleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied.
        /// </summary>
        public static string txtCopied {
            get {
                return ResourceManager.GetString("txtCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copying errors.
        /// </summary>
        public static string txtCopyinErr {
            get {
                return ResourceManager.GetString("txtCopyinErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check of files done in.
        /// </summary>
        public static string txtDoneIn {
            get {
                return ResourceManager.GetString("txtDoneIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy made in.
        /// </summary>
        public static string txtDoneOut {
            get {
                return ResourceManager.GetString("txtDoneOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found.
        /// </summary>
        public static string txtFound {
            get {
                return ResourceManager.GetString("txtFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new or modified files.
        /// </summary>
        public static string txtNewNoSize {
            get {
                return ResourceManager.GetString("txtNewNoSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new or modified files for a size of.
        /// </summary>
        public static string txtNewSize {
            get {
                return ResourceManager.GetString("txtNewSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new or modified files for a total size of .
        /// </summary>
        public static string txtNewTotSize {
            get {
                return ResourceManager.GetString("txtNewTotSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no copy errors.
        /// </summary>
        public static string txtNoCopyErr {
            get {
                return ResourceManager.GetString("txtNoCopyErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not files to copy: the &apos;Copy&apos; button is not activated.
        /// </summary>
        public static string txtNoFileToCopy {
            get {
                return ResourceManager.GetString("txtNoFileToCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to over.
        /// </summary>
        public static string txtOver {
            get {
                return ResourceManager.GetString("txtOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the &quot;Open CF2.log&quot; button to read the files list.
        /// </summary>
        public static string txtPressOpen {
            get {
                return ResourceManager.GetString("txtPressOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors and skipped files full list at the bottom of the list.
        /// </summary>
        public static string txtPressOpen2 {
            get {
                return ResourceManager.GetString("txtPressOpen2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row n..
        /// </summary>
        public static string txtRowN {
            get {
                return ResourceManager.GetString("txtRowN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string txtSeconds {
            get {
                return ResourceManager.GetString("txtSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mom please, filtering not modified files....
        /// </summary>
        public static string txtSkipping {
            get {
                return ResourceManager.GetString("txtSkipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying.
        /// </summary>
        public static string txtStartCopy {
            get {
                return ResourceManager.GetString("txtStartCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starting path.
        /// </summary>
        public static string txtStartingPath {
            get {
                return ResourceManager.GetString("txtStartingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total report: found.
        /// </summary>
        public static string txtTotalFound {
            get {
                return ResourceManager.GetString("txtTotalFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total seconds.
        /// </summary>
        public static string txtTotSeconds {
            get {
                return ResourceManager.GetString("txtTotSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled error .
        /// </summary>
        public static string Unhandled {
            get {
                return ResourceManager.GetString("Unhandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A program update is available.
        ///Click &apos;Yes&apos; if you want to download it now, otherwise, click &apos;No&apos;..
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CopyFolders2 will be closed..
        /// </summary>
        public static string WillClosed {
            get {
                return ResourceManager.GetString("WillClosed", resourceCulture);
            }
        }
    }
}
